<?php require('template/header.phtml') ?>

<h3>Welcome to Red Summit Support Solutions</h3>
<p>These pages are made up by seperating elements that would originally be on one html page
into seperate pieces. Therefore only requiring one line of code so that the page displays them. This means we can add extra
functionality easier down the line. Instead of having to copy paste our header, footer and sidebars into each page. We can just
add all the content that is new and all the things we expect to be on every page like the navbar will be there</p>
<?php require('template/footer.phtml') ?>
