<?php require('template/header.phtml') ?>

<h3>Make your complaint here!</h3>
<form action="formhandling.php" method="post">
    Name: <input type="text" name="name"><br>
    E-mail: <input type="text" name="email"><br>
    Ready To Complain:<br>
    <input type="radio" name="complain" value="yes" checked> Yes<br>
    <input type="radio" name="complain" value="yes"> No<br>

    <input type="submit">
</form>
<?php require('template/footer.phtml') ?>
