    </div>


    <div class-"row">
        <div id="footer" class="col-xs-12">
            <p>Web-site development using the MVC design pattern and the Bootstrap CSS framework</p>
        </div>
    </div>
<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="/js/jquery-3.2.1.min.js"></script>
<!--<script src="js/bootstrap.min.js"></script>-->
</body>
</html>